using Common.Constants;
using MiniRedis.Enums;
using MiniRedis.Models.GlobalCache;
using MiniRedis.Models.RedisStream;

namespace MiniRedis.Commands.Requests
{
    public class XReadRequest
    {
        private const int MinimumArgs = 4;
        public IReadOnlyList<XReadStreamQuery> Queries { get; private set; } = [];

        private XReadRequest(List<XReadStreamQuery> queries)
        {
            Queries = queries;
        }

        public static XReadRequest Create(List<string> args)
        {
            if (args.Count < MinimumArgs || !args[1].Equals("STREAMS", StringComparison.InvariantCultureIgnoreCase))
            {
                throw new InvalidOperationException(RedisErrorMessages.InvalidArgument);
            }

            var argsValues = args[2..];
            if (argsValues.Count % 2 != 0)
            {
                throw new InvalidOperationException(RedisErrorMessages.XRead.UnbalancedXREADArgs);
            }

            List<XReadStreamQuery> queries = [];
            var streamIds = argsValues[..(argsValues.Count / 2)];
            var dataIds = argsValues[(argsValues.Count / 2)..];
            var currentIndex = 0;
            foreach (var id in streamIds)
            {
                if (!RedisStreamDataId.TryParseXRangeStreamDataId(dataIds[currentIndex], out var startTimestamp, out var startSequenceNumber, out var startPattern) || 
                    startPattern == StreamDataIdPattern.FullyAuto)
                {
                    throw new InvalidOperationException(RedisErrorMessages.InvalidArgument);
                }
                var entry = new RedisEntry { Key = id };

                if (startPattern == StreamDataIdPattern.AutoGeneratedSequence)
                {
                    startSequenceNumber = 0;
                }
                var dataId = RedisStreamDataId.Create(startTimestamp!.Value, startSequenceNumber!.Value, StreamDataIdPattern.FullForm, skipValidation: true);

                var query = XReadStreamQuery.Create(new RedisEntry { Key = id }, dataId);
                queries.Add(query);
                currentIndex++;
            }

            return new XReadRequest(queries);
        }
    }
}
