using Common.Constants;
using MiniRedis.Enums;
using MiniRedis.Models.GlobalCache;
using MiniRedis.Models.RedisStream;

namespace MiniRedis.Commands.Requests;

public class XReadRequest
{
    private const int MinimumArgs = 4;
    public IReadOnlyList<XReadStreamQuery> Queries { get; private set; }
    public float? TimeoutInMilliseconds { get; }
    public bool IsBlockingRequest { get; }

    private XReadRequest(List<XReadStreamQuery> queries, float? timeoutInSeconds, bool isBlockingRequest)
    {
        Queries = queries;
        TimeoutInMilliseconds = timeoutInSeconds;
        IsBlockingRequest = isBlockingRequest;
    }

    public static XReadRequest Create(List<string> args)
    {
        float? timeoutInMilliseconds = null;
        var isBlockingRequest = false;
        if (args.Count < MinimumArgs || !args[1].Equals("STREAMS", StringComparison.InvariantCultureIgnoreCase) && !args[1].Equals("BLOCK", StringComparison.InvariantCultureIgnoreCase))
        {
            throw new InvalidOperationException(RedisErrorMessages.InvalidArgument);
        }

        if (args[1].Equals("BLOCK", StringComparison.InvariantCultureIgnoreCase))
        {
            isBlockingRequest = true;
            if (!float.TryParse(args[2], out var parsedTimeoutInMillisecond) && !args[2].Equals("STREAMS", StringComparison.InvariantCultureIgnoreCase) || parsedTimeoutInMillisecond < 0)
            {
                throw new InvalidOperationException(RedisErrorMessages.InvalidArgument);
            }
            else
            {
                timeoutInMilliseconds = parsedTimeoutInMillisecond;
            }
        }

        var idStartingIndex = isBlockingRequest ? 4 : 2;
        var argsValues = args[idStartingIndex..];
        if (argsValues.Count % 2 != 0)
        {
            throw new InvalidOperationException(RedisErrorMessages.XRead.UnbalancedXREADArgs);
        }

        List<XReadStreamQuery> queries = [];
        var streamIds = argsValues[..(argsValues.Count / 2)];
        var dataIds = argsValues[(argsValues.Count / 2)..];
        var currentIndex = 0;
        foreach (var id in streamIds)
        {
            if (!RedisStreamDataId.TryParseXRangeStreamDataId(dataIds[currentIndex], out var startTimestamp, out var startSequenceNumber, out var startPattern) ||
                startPattern == StreamDataIdPattern.FullyAuto)
            {
                throw new InvalidOperationException(RedisErrorMessages.InvalidArgument);
            }

            if (startPattern == StreamDataIdPattern.AutoGeneratedSequence)
            {
                startSequenceNumber = 0;
            }

            var dataId = RedisStreamDataId.Create(startTimestamp!.Value, startSequenceNumber!.Value);

            var query = XReadStreamQuery.Create(new RedisEntry { Key = id }, dataId);
            queries.Add(query);
            currentIndex++;
        }

        return new XReadRequest(queries, timeoutInMilliseconds, isBlockingRequest);
    }
}