using Common.Constants;
using Common.Helpers;
using MiniRedis.Constants;
using MiniRedis.Data;
using MiniRedis.Enums;
using MiniRedis.Models.GlobalCache;
using MiniRedis.Models.RedisStream;
using System.Net.Sockets;

namespace MiniRedis.Commands;

public class XAddCommand : ICommand
{
    public int Arity => 5;
    public bool IsWriteCommand => true;

    public async Task<string> ExecuteAsync(List<string> args, RedisDatabase database, Socket client)
    {
        var streamEntryKey = new RedisEntry { Key = args[1] };
        var streamDataId = args[2];
        var streamDataValuesArg = args[3..];

        var parsedStreamDataValues = BuildRedisValuesFromArgs(streamDataValuesArg);

        return await Task.FromResult(database.XAdd(streamEntryKey, streamDataId, parsedStreamDataValues));
    }

    private static List<RedisStreamDataValue> BuildRedisValuesFromArgs(List<string> values)
    {
        List<RedisStreamDataValue> result = [];
        for (var i = 0; i < values.Count - 1; i += 2)
        {
            result.Add(RedisStreamDataValue.Create(values[i], values[i + 1]));
        }

        return result;
    }

    public static RedisStreamDataId AddDataRangeToCache(string streamId, string dataId, List<RedisStreamDataValue> streamDataValues, Dictionary<RedisEntry, RedisValue> cache)
    {
        var newStreamData = CreateNewStreamData(streamId, dataId, streamDataValues, cache, out var idGenerationBehaviour);
        var newDataId = newStreamData.GetCurrentLargestId()!;

        var cacheKey = new RedisEntry { Key = streamId };
        var cacheValue = new RedisValue(newStreamData);

        if (!cache.TryGetValue(cacheKey, out var streamData))
        {
            cache.Add(cacheKey, cacheValue);
            return newDataId;
        }

        var parsedStreamData = streamData.AsStream();
        RedisStreamDataId.ValidateDataId(idGenerationBehaviour, newDataId, parsedStreamData);
        return parsedStreamData.AddRange(newDataId, streamDataValues, idGenerationBehaviour);
    }

    private static RedisStreamData CreateNewStreamData(string streamId, string dataId, List<RedisStreamDataValue> streamDataValues, 
        Dictionary<RedisEntry, RedisValue> cache, out StreamDataIdGenerationBehaviour idGenerationBehaviour)
    {
        var baseNewDataId = GenerateNewDataId(streamId, dataId, cache, out idGenerationBehaviour);
        return RedisStreamData.Create(baseNewDataId, streamDataValues, idGenerationBehaviour);
    }

    private static RedisStreamDataId GenerateNewDataId(string streamId, string dataId, Dictionary<RedisEntry, RedisValue> cache,
        out StreamDataIdGenerationBehaviour generationBehaviour)
    {
        var cacheKey = new RedisEntry { Key = streamId };
        if (!RedisStreamDataId.TryParseStreamDataId(dataId, out var timestamp, out var sequence,
                out var dataIdGenerationBehaviour))
        {
            throw new InvalidOperationException(RedisErrorMessages.XAddStreamDataIdNotGreaterThan0);
        }
        generationBehaviour = dataIdGenerationBehaviour;

        var hasExistingStream = cache.TryGetValue(cacheKey, out var streamData);
        var defaultSequenceForAutogeneratedSequence = timestamp!.Value == 0
            ? StreamConstants.DefaultSequenceNumberForZeroTimestamp
            : StreamConstants.DefaultSequenceNumberForNonZeroTimestamp;

        return dataIdGenerationBehaviour switch
        {
            StreamDataIdGenerationBehaviour.FullyAuto => RedisStreamDataId.Create(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
                StreamConstants.DefaultSequenceNumberForNonZeroTimestamp, dataIdGenerationBehaviour),
            StreamDataIdGenerationBehaviour.AutoGeneratedSequence => hasExistingStream
                ? streamData!.AsStream().GetNextId(timestamp.Value, dataIdGenerationBehaviour)
                : RedisStreamDataId.Create(timestamp.Value, defaultSequenceForAutogeneratedSequence, dataIdGenerationBehaviour),
            StreamDataIdGenerationBehaviour.Manual => RedisStreamDataId.Create(timestamp!.Value, sequence!.Value, dataIdGenerationBehaviour),
            _ => throw new ArgumentOutOfRangeException()
        };
    }
}