using Common.Constants;
using Common.Results;
using MiniRedis.Commands.AsyncManagers;
using MiniRedis.Commands.Requests;
using MiniRedis.Constants;
using MiniRedis.Enums;
using MiniRedis.Models;
using MiniRedis.Models.GlobalCache;
using MiniRedis.Models.RedisStream;

namespace MiniRedis.Data
{
    public class StreamStore
    {
        private readonly Dictionary<RedisEntry, RedisValue> _cache;

        public StreamStore(Dictionary<RedisEntry, RedisValue> cache)
        {
            _cache = cache;
        }

        public RedisStreamDataId XAdd(RedisEntry streamEntryKey, string streamDataId, List<RedisStreamDataValue> parsedStreamDataValues)
        {
            var result = AddDataRangeToCache(streamEntryKey, streamDataId, parsedStreamDataValues);
            BlockingManager.SignalLongestClient(streamEntryKey.Key);
            return result;
        }

        public List<StreamDataResult>? XRange(RedisEntry cacheKey, string startId, string endId, XRangeCommandPurpose purpose)
        {
            if (!_cache.TryGetValue(cacheKey, out var value))
            {
                return null;
            }

            var startPattern = StreamDataIdPattern.FullForm;
            long? startTimestamp = null;
            long? startSequenceNumber = null;
            var endPattern = StreamDataIdPattern.FullForm;
            long? endTimestamp = null;
            long? endSequenceNumber = null;
            if ((purpose != XRangeCommandPurpose.QueryWithStartArgument &&
                 !RedisStreamDataId.TryParseXRangeStreamDataId(startId, out startTimestamp, out startSequenceNumber, out startPattern)) ||
                (purpose != XRangeCommandPurpose.QueryWithEndArgument &&
                 !RedisStreamDataId.TryParseXRangeStreamDataId(endId, out endTimestamp, out endSequenceNumber, out endPattern)))
            {
                throw new InvalidOperationException(RedisErrorMessages.XAddStreamDataIdInvalidFormat);
            }

            if ((purpose != XRangeCommandPurpose.QueryWithStartArgument && startPattern != StreamDataIdPattern.FullForm &&
                 startPattern != StreamDataIdPattern.AutoGeneratedSequence) ||
                (purpose != XRangeCommandPurpose.QueryWithEndArgument && endPattern != StreamDataIdPattern.FullForm && endPattern != StreamDataIdPattern.AutoGeneratedSequence))
            {
                throw new InvalidOperationException(RedisErrorMessages.XAddStreamDataIdInvalidFormat);
            }

            var streamData = value.AsStream();
            if (startPattern == StreamDataIdPattern.AutoGeneratedSequence)
            {
                startSequenceNumber = 0;
            }

            if (endPattern == StreamDataIdPattern.AutoGeneratedSequence)
            {
                endSequenceNumber = streamData.GetCurrentLargestId(endTimestamp!.Value)?.Sequence ?? 0;
            }

            RedisStreamDataId? parsedStartId = null;
            if (purpose != XRangeCommandPurpose.QueryWithStartArgument)
            {
                parsedStartId = RedisStreamDataId.Create(startTimestamp!.Value, startSequenceNumber.Value);
            }

            RedisStreamDataId? parsedEndId = null;
            if (purpose != XRangeCommandPurpose.QueryWithEndArgument)
            {
                parsedEndId = RedisStreamDataId.Create(endTimestamp!.Value, endSequenceNumber!.Value);
            }

            return streamData
                .GetRange(parsedStartId, parsedEndId)
                .Select(kp =>
                    new StreamDataResult(
                        kp.Key.ToString(),
                        kp.Value.SelectMany(v => v.ToKeyValueStringArray()).ToList()))
                .ToList();
        }

        public List<XReadStreamResult> XRead(XReadRequest request)
        {
            List<XReadStreamResult> results = [];
            foreach (var query in request.Queries)
            {
                var cacheKey = query.StreamId;
                var startId = query.DataId;

                if (!_cache.TryGetValue(cacheKey, out var value))
                {
                    results.Add(new XReadStreamResult(cacheKey.Key, null));
                    continue;
                }

                var streamData = value.AsStream();

                List<StreamDataResult>? result;
                if (request.IsBlockingRequest && request.HasStartingIdSign)
                {
                    var lastData = streamData.GetLast(startId);

                    if(lastData == null)
                    {
                        result = [];
                    }
                    else
                    {
                        result = [new StreamDataResult(
                            lastData.Value.Key.ToString(),
                            lastData.Value.Value.SelectMany(v => v.ToKeyValueStringArray()).ToList())];
                    }
                }
                else
                {
                    result = streamData
                    .GetRangeGreaterThan(startId)
                    .Select(kp =>
                        new StreamDataResult(
                            kp.Key.ToString(),
                            kp.Value.SelectMany(v => v.ToKeyValueStringArray()).ToList()))
                    .ToList();
                }

                results.Add(new XReadStreamResult(cacheKey.Key, result));
            }

            return results;
        }

        private RedisStreamDataId AddDataRangeToCache(RedisEntry streamId, string dataId, List<RedisStreamDataValue> streamDataValues)
        {
            var newDataId = GenerateNewDataId(streamId.Key, dataId, out var idGenerationBehaviour);

            if (!_cache.TryGetValue(streamId, out var streamData))
            {
                streamData = new RedisValue(RedisStreamData.Empty());
                _cache.Add(streamId, streamData);
            }

            var parsedStreamData = streamData.AsStream();
            return parsedStreamData.AddRange(newDataId, streamDataValues, idGenerationBehaviour);
        }

        private RedisStreamDataId GenerateNewDataId(string streamId, string dataId, out StreamDataIdPattern pattern)
        {
            var cacheKey = new RedisEntry { Key = streamId };
            if (!RedisStreamDataId.TryParseStreamDataId(dataId, out var timestamp, out var sequence, out var dataIdGenerationBehaviour))
            {
                throw new InvalidOperationException(RedisErrorMessages.XAddStreamDataIdNotGreaterThan0);
            }

            pattern = dataIdGenerationBehaviour;

            var hasExistingStream = _cache.TryGetValue(cacheKey, out var streamData);
            var defaultSequenceForAutogeneratedSequence = timestamp == 0
                ? StreamConstants.DefaultSequenceNumberForZeroTimestamp
                : StreamConstants.DefaultSequenceNumberForNonZeroTimestamp;

            return dataIdGenerationBehaviour switch
            {
                StreamDataIdPattern.FullyAuto => RedisStreamDataId.Create(
                    DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(), StreamConstants.DefaultSequenceNumberForNonZeroTimestamp),
                StreamDataIdPattern.AutoGeneratedSequence => hasExistingStream
                    ? streamData!.AsStream().GetNextId(timestamp!.Value, dataIdGenerationBehaviour)
                    : RedisStreamDataId.Create(timestamp!.Value, defaultSequenceForAutogeneratedSequence),
                StreamDataIdPattern.FullForm => RedisStreamDataId.Create(timestamp!.Value, sequence!.Value),
                _ => throw new ArgumentOutOfRangeException()
            };
        }
    }
}
