using Common.Constants;
using MiniRedis.Enums;

namespace MiniRedis.Models.RedisStream;

public record RedisStreamDataId
{
    public long Timestamp { get; private set; }
    public long Sequence { get; private set; }

    private RedisStreamDataId(long timestamp, long sequence)
    {
        Timestamp = timestamp;
        Sequence = sequence;
    }

    public static RedisStreamDataId Create(long timestamp, long sequence)
    {
        return new RedisStreamDataId(timestamp, sequence);
    }

    public static bool TryParseStreamDataId(string input, out long? timestamp, out long? sequenceNumber, out StreamDataIdPattern dataIdPattern)
    {
        dataIdPattern = StreamDataIdPattern.FullForm;
        timestamp = null;
        sequenceNumber = null;

        if (input.Trim() == "*")
        {
            dataIdPattern = StreamDataIdPattern.FullyAuto;
            return true;
        }

        var parts = input.Split('-');
        if (parts.Length != 2)
        {
            return false;
        }

        if (!long.TryParse(parts[0], out var time) || time < 0)
        {
            return false;
        }

        timestamp = time;

        if (parts[1] == "*")
        {
            dataIdPattern = StreamDataIdPattern.AutoGeneratedSequence;
            return true;
        }

        if (!long.TryParse(parts[1], out var sequence) || sequence < 0)
        {
            return false;
        }

        sequenceNumber = sequence;

        return true;
    }

    public static bool TryParseXRangeStreamDataId(string input, out long? timestamp, out long? sequenceNumber, out StreamDataIdPattern dataIdPattern)
    {
        dataIdPattern = StreamDataIdPattern.FullForm;
        timestamp = null;
        sequenceNumber = null;

        if (input.Trim() == "*")
        {
            dataIdPattern = StreamDataIdPattern.FullyAuto;
            return true;
        }

        var parts = input.Split('-');
        if (parts.Length < 1 || parts.Length > 2)
        {
        }

        if (!long.TryParse(parts[0], out var time) || time < 0)
        {
            return false;
        }

        timestamp = time;

        if (parts.Length == 1 || parts[1] == "*")
        {
            dataIdPattern = StreamDataIdPattern.AutoGeneratedSequence;
            return true;
        }

        if (!long.TryParse(parts[1], out var sequence) || sequence < 0)
        {
            return false;
        }

        sequenceNumber = sequence;

        return true;
    }

    public RedisStreamDataId GetNextId() => new(Timestamp, Sequence + 1);
    public static RedisStreamDataId GetNextId(RedisStreamDataId currentId) => new(currentId.Timestamp, currentId.Sequence + 1);

    public override string ToString()
    {
        var timeStamp = Timestamp.ToString();
        var sequence = Sequence.ToString();
        return $"{timeStamp}-{sequence}";
    }

    internal static bool IsGreaterThan(RedisStreamDataId newId, RedisStreamDataId? existingId)
    {
        if (existingId is null)
        {
            return true;
        }

        return newId.Timestamp > existingId.Timestamp ||
               (newId.Timestamp == existingId.Timestamp && newId.Sequence > existingId.Sequence);
    }
}