using Common.Constants;
using MiniRedis.Enums;

namespace MiniRedis.Models.RedisStream;

public record RedisStreamDataId
{
    public long Timestamp { get; private set; }
    public long Sequence { get; private set; }
    private StreamDataIdGenerationBehaviour IdGenerationBehaviour { get; }

    private RedisStreamDataId(long timestamp, long sequence, StreamDataIdGenerationBehaviour idGenerationBehaviour)
    {
        if (idGenerationBehaviour == StreamDataIdGenerationBehaviour.Manual && timestamp == 0 && sequence == 0)
        {
            throw new InvalidOperationException(RedisErrorMessages.XAddStreamDataIdNotGreaterThan0);
        }

        Timestamp = timestamp;
        Sequence = sequence;
        IdGenerationBehaviour = idGenerationBehaviour;
    }

    public static RedisStreamDataId Create(long timestamp, long sequence, StreamDataIdGenerationBehaviour idGenerationBehaviour)
    {
        return new RedisStreamDataId(timestamp, sequence, idGenerationBehaviour);
    }

    public static bool TryParseStreamDataId(string input, out long? timestamp, out long? sequenceNumber,
        out StreamDataIdGenerationBehaviour dataIdGenerationBehaviour)
    {
        dataIdGenerationBehaviour = StreamDataIdGenerationBehaviour.Manual;
        timestamp = null;
        sequenceNumber = null;

        if (input.Trim() == "*")
        {
            dataIdGenerationBehaviour = StreamDataIdGenerationBehaviour.FullyAuto;
            return true;
        }

        var parts = input.Split('-');
        if (parts.Length != 2)
        {
            return false;
        }

        if (!long.TryParse(parts[0], out var time) || time < 0)
        {
            return false;
        }

        timestamp = time;

        if (parts[1] == "*")
        {
            dataIdGenerationBehaviour = StreamDataIdGenerationBehaviour.AutoGeneratedSequence;
            return true;
        }

        if (!long.TryParse(parts[1], out var sequence) || sequence < 0)
        {
            return false;
        }

        sequenceNumber = sequence;

        return true;
    }

    public static void ValidateDataId(StreamDataIdGenerationBehaviour idGenerationBehaviour, RedisStreamDataId newDataId, RedisStreamData streamData)
    {
        if (idGenerationBehaviour != StreamDataIdGenerationBehaviour.Manual)
        {
            return;
        }

        if (!IsGreaterThan(newDataId, streamData.GetCurrentLargestId()))
        {
            throw new InvalidOperationException(RedisErrorMessages.XAddStreamDataIdSmallerThanTopItem);
        }
    }

    public RedisStreamDataId GetNextId(StreamDataIdGenerationBehaviour idGenerationBehaviour) => new(Timestamp, Sequence + 1, idGenerationBehaviour);
    public static RedisStreamDataId GetNextId(RedisStreamDataId currentId, StreamDataIdGenerationBehaviour idGenerationBehaviour) => new(currentId.Timestamp, currentId.Sequence + 1, idGenerationBehaviour);

    public override string ToString()
    {
        var timeStamp = Timestamp.ToString();
        var sequence = Sequence.ToString();
        return $"{timeStamp}-{sequence}";
    }

    private static bool IsGreaterThan(RedisStreamDataId newId, RedisStreamDataId? existingId)
    {
        if (existingId is null)
        {
            return true;
        }

        return newId.Timestamp > existingId.Timestamp ||
               (newId.Timestamp == existingId.Timestamp && newId.Sequence > existingId.Sequence);
    }

}